// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "DetailConfigWindow.h"

void DetailConfigWindow::cb_Dismiss_i(Fl_Return_Button*, void*) {
  table->EndEditing();
hide();
}
void DetailConfigWindow::cb_Dismiss(Fl_Return_Button* o, void* v) {
  ((DetailConfigWindow*)(o->parent()))->cb_Dismiss_i(o,v);
}

void DetailConfigWindow::cb_inputFilter_i(Fl_Input*, void*) {
  onFilterChange();
}
void DetailConfigWindow::cb_inputFilter(Fl_Input* o, void* v) {
  ((DetailConfigWindow*)(o->parent()))->cb_inputFilter_i(o,v);
}
DetailConfigWindow::DetailConfigWindow(int X, int Y, int W, int H, const char *L)
  : Fl_Window(X, Y, W, H, L) {
  _DetailConfigWindow();
}

DetailConfigWindow::DetailConfigWindow(int W, int H, const char *L)
  : Fl_Window(0, 0, W, H, L) {
  clear_flag(16);
  _DetailConfigWindow();
}

DetailConfigWindow::DetailConfigWindow()
  : Fl_Window(0, 0, 591, 513, "Advanced Settings") {
  clear_flag(16);
  _DetailConfigWindow();
}

void DetailConfigWindow::_DetailConfigWindow() {
this->box(FL_FLAT_BOX);
this->color(FL_BACKGROUND_COLOR);
this->selection_color(FL_BACKGROUND_COLOR);
this->labeltype(FL_NO_LABEL);
this->labelfont(0);
this->labelsize(14);
this->labelcolor(FL_FOREGROUND_COLOR);
this->align(Fl_Align(FL_ALIGN_TOP));
this->when(FL_WHEN_RELEASE);
{ Fl_Return_Button* o = new Fl_Return_Button(480, 475, 100, 25, "Dismiss");
  o->callback((Fl_Callback*)cb_Dismiss);
} // Fl_Return_Button* o
{ table = new DetailConfigTable(10, 35, 570, 430);
  table->box(FL_THIN_DOWN_FRAME);
  table->color(FL_BACKGROUND_COLOR);
  table->selection_color(FL_BACKGROUND_COLOR);
  table->labeltype(FL_NORMAL_LABEL);
  table->labelfont(0);
  table->labelsize(14);
  table->labelcolor(FL_FOREGROUND_COLOR);
  table->align(Fl_Align(FL_ALIGN_TOP));
  table->when(FL_WHEN_RELEASE);
  table->end();
} // DetailConfigTable* table
{ inputFilter = new Fl_Input(50, 11, 530, 24, "Filter:");
  inputFilter->callback((Fl_Callback*)cb_inputFilter);
  inputFilter->when(FL_WHEN_CHANGED);
} // Fl_Input* inputFilter
end();
}
