// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef DetailConfigWindow_h
#define DetailConfigWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include "DetailConfigTable.h"
#include <FL/Fl_Return_Button.H>

class DetailConfigWindow : public Fl_Window {
  void _DetailConfigWindow();
public:
  DetailConfigWindow(int X, int Y, int W, int H, const char *L = 0);
  DetailConfigWindow(int W, int H, const char *L = 0);
  DetailConfigWindow();
private:
  inline void cb_Dismiss_i(Fl_Return_Button*, void*);
  static void cb_Dismiss(Fl_Return_Button*, void*);
public:
  DetailConfigTable *table;
  void Init();
};
#endif
