// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef ErrorDialog_h
#define ErrorDialog_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>

class ErrorDialog : public Fl_Window {
  void _ErrorDialog();
public:
  ErrorDialog(int X, int Y, int W, int H, const char *L = 0);
  ErrorDialog(int W, int H, const char *L = 0);
  ErrorDialog();
  Fl_Text_Display *infoView;
private:
  inline void cb_OK_i(Fl_Return_Button*, void*);
  static void cb_OK(Fl_Return_Button*, void*);
  inline void cb_Quit_i(Fl_Button*, void*);
  static void cb_Quit(Fl_Button*, void*);
public:
  int result; 
  Fl_Output *helpView;
};
#endif
