// This header file is provided for the Xcode project.
// In other platforms, please use OpenSpades.h generated by CMake.

#define OpenSpades_VERSION_MAJOR 0
#define OpenSpades_VERSION_MINOR 1
#define OpenSpades_VERSION_REVISION 2

#define OS_STRINGIFY2(x)	#x
#define OS_STRINGIFY(x)		OS_STRINGIFY2(x)

#define OpenSpades_VER_STR	"OpenSpades 0.1.0 for OS X"
#define PACKAGE_STRING		OpenSpades_VER_STR

/* #undef HAS_OPENAL */

/* #undef RESDIR_DEFINED */
//#define RESDIR ""
