
uniform sampler2D texture;

varying vec4 texCoord1;
varying vec4 texCoord2;

void main() {
	// generated by ./1dgaussGen.rb
	// pixelShift is texture coord shift / texture pixel
	const float pixelShift = 1.;
	const float shift1 = pixelShift * -2.30654399138844;
	const float scale1 = 0.178704407070903;
	const float shift2 = pixelShift * -0.629455560633963;
	const float scale2 = 0.321295592929097;
	const float shift3 = pixelShift * 0.629455560633963;
	const float scale3 = 0.321295592929097;
	const float shift4 = pixelShift * 2.30654399138844;
	const float scale4 = 0.178704407070903;
	
	gl_FragColor = texture2D(texture, texCoord1.xy) * scale1;
	gl_FragColor += texture2D(texture, texCoord1.zw) * scale2;
	gl_FragColor += texture2D(texture, texCoord2.xy) * scale3;
	gl_FragColor += texture2D(texture, texCoord2.zw) * scale4;
}

